module Moto
  module Reporting
    module Listeners

      # Base class for listeners that report results of testing 'outside' of the application.
      class Base

        attr_reader :suite_name
        attr_reader :run_name

        # @param [String] suite_name Name that identifies the suite, passed by user or autogenerated
        # @param [String] run_name Name that identifies the run, passed by user or autogenerated
        def initialize(suite_name, run_name)
          @suite_name = suite_name

          @run_name = run_name
        end

        # Invoked when whole batch of tests starts
        def start_run
          # Abstract
        end

        # Abstract
        # Invoked when whole batch of tests ends
        def end_run(run_status)
          # Abstract
        end

        # Abstract
        # Invoked when a single test is started
        def start_test(test_status)
          # Abstract
        end

        # Abstract
        # Invoked when a single test is finished
        def end_test(test_status)
          # Abstract
        end

      end
    end
  end
end